// 实用工具箱 - 主逻辑模块
(function() {
  'use strict';
  const data = window.TOOLBOX_DATA || {};
  const CATEGORIES = data.CATEGORIES || [];
  const HOT_TOOLS = data.HOT_TOOLS || [];
  const CATEGORY_GUIDES = data.CATEGORY_GUIDES || {};
  const TOOL_GUIDES = data.TOOL_GUIDES || {};
  const BLOG_POSTS = data.BLOG_POSTS || [];
  const FAQ_ITEMS = data.FAQ_ITEMS || [];
  let currentCategory = 'all';
  let currentPage = 'home';
  let currentBlogId = null;
  let favoriteTools = [];
  let recentTools = [];
  function loadFavorites() { try { const saved = localStorage.getItem('favoriteTools'); favoriteTools = saved ? JSON.parse(saved) : []; } catch(e) { favoriteTools = []; } }
  function saveFavorites() { try { localStorage.setItem('favoriteTools', JSON.stringify(favoriteTools)); } catch(e) {} }
  function toggleFavorite(toolId) { const idx = favoriteTools.indexOf(toolId); if (idx > -1) favoriteTools.splice(idx, 1); else favoriteTools.push(toolId); saveFavorites(); return favoriteTools.includes(toolId); }
  function isFavorite(toolId) { return favoriteTools.includes(toolId); }
  function addRecentTool(toolId) { const idx = recentTools.indexOf(toolId); if (idx > -1) recentTools.splice(idx, 1); recentTools.unshift(toolId); if (recentTools.length > 8) recentTools = recentTools.slice(0, 8); try { localStorage.setItem('recentTools', JSON.stringify(recentTools)); } catch(e) {} }
  function loadRecentTools() { try { const saved = localStorage.getItem('recentTools'); recentTools = saved ? JSON.parse(saved) : []; } catch(e) { recentTools = []; } }
  document.addEventListener('DOMContentLoaded', function() {
    loadFavorites(); loadRecentTools(); initTheme(); renderCategories(); renderCategoryGrid(); renderTools(); renderHotTools(); renderFavoriteTools(); renderRecentTools(); renderBlogList(); renderLatestBlog(); renderHotBlog(); renderBlogCategories(); renderFAQ(); bindEvents(); initAdSense(); handleHash();
  });
  function initTheme() { const saved = localStorage.getItem('theme'); if (saved === 'dark') document.body.classList.add('dark'); document.getElementById('themeToggle').textContent = document.body.classList.contains('dark') ? '☀️' : '🌙'; }
  function toggleTheme() { document.body.classList.toggle('dark'); const isDark = document.body.classList.contains('dark'); localStorage.setItem('theme', isDark ? 'dark' : 'light'); document.getElementById('themeToggle').textContent = isDark ? '☀️' : '🌙'; }
  function renderCategories() { const list = document.getElementById('categoryList'); list.innerHTML = CATEGORIES.map(cat => { const count = cat.id === 'all' ? TOOLS.length : TOOLS.filter(t => t.category === cat.id).length; return `<div class="category-item ${currentCategory === cat.id ? 'active' : ''}" data-cat="${cat.id}"><span class="cat-icon">${cat.icon}</span><span class="cat-name">${cat.name}</span><span class="cat-count">${count}</span></div>`; }).join(''); }
  function renderCategoryGrid() { const grid = document.getElementById('categoryGrid'); const cats = CATEGORIES.filter(c => c.id !== 'all'); grid.innerHTML = cats.map(cat => { const count = TOOLS.filter(t => t.category === cat.id).length; return `<div class="category-card" data-cat="${cat.id}"><div class="cat-card-icon">${cat.icon}</div><h3>${cat.name}</h3><p>${count} 个工具</p></div>`; }).join(''); }
  function renderHotTools() { const grid = document.getElementById('hotToolsGrid'); if (!grid) return; const hotTools = HOT_TOOLS.map(id => TOOLS.find(t => t.id === id)).filter(Boolean); grid.innerHTML = hotTools.map(t => `<div class="tool-card hot-tool-card" data-tool="${t.id}"><div class="tool-icon">${t.icon}</div><h3 class="tool-name">${t.name}</h3><p class="tool-desc">${t.desc}</p><span class="tool-cat">${t.category}</span></div>`; }).join(''); }
  function renderFavoriteTools() { const grid = document.getElementById('favoriteToolsGrid'); if (!grid) return; const section = document.getElementById('favoriteSection'); if (favoriteTools.length === 0) { if (section) section.style.display = 'none'; return; } if (section) section.style.display = 'block'; const favTools = favoriteTools.map(id => TOOLS.find(t => t.id === id)).filter(Boolean); grid.innerHTML = favTools.map(t => `<div class="tool-card" data-tool="${t.id}"><div class="tool-icon">${t.icon}</div><h3 class="tool-name">${t.name}</h3><p class="tool-desc">${t.desc}</p><span class="tool-cat">${t.category}</span></div>`; }).join(''); }
  function renderRecentTools() { const grid = document.getElementById('recentToolsGrid'); if (!grid) return; const section = document.getElementById('recentSection'); if (recentTools.length === 0) { if (section) section.style.display = 'none'; return; } if (section) section.style.display = 'block'; const recTools = recentTools.map(id => TOOLS.find(t => t.id === id)).filter(Boolean); grid.innerHTML = recTools.map(t => `<div class="tool-card" data-tool="${t.id}"><div class="tool-icon">${t.icon}</div><h3 class="tool-name">${t.name}</h3><p class="tool-desc">${t.desc}</p><span class="tool-cat">${t.category}</span></div>`; }).join(''); }
  function renderTools(keyword) { const grid = document.getElementById('toolsGrid'); let filtered = TOOLS; if (currentCategory !== 'all') filtered = filtered.filter(t => t.category === currentCategory); if (keyword && keyword.trim()) { const kw = keyword.toLowerCase(); filtered = filtered.filter(t => t.name.toLowerCase().includes(kw) || t.desc.toLowerCase().includes(kw) || t.category.toLowerCase().includes(kw)); } if (filtered.length === 0) { grid.innerHTML = '<div style="grid-column:1/-1;text-align:center;padding:60px;color:var(--text-secondary)">未找到匹配的工具</div>'; return; } grid.innerHTML = filtered.map(t => `<div class="tool-card" data-tool="${t.id}"><div class="tool-icon">${t.icon}</div><h3 class="tool-name">${t.name}</h3><p class="tool-desc">${t.desc}</p><span class="tool-cat">${t.category}</span></div>`; }).join(''); }
  function showTool(toolId) {
    const tool = TOOLS.find(t => t.id === toolId);
    if (!tool) return;
    document.getElementById('toolsGrid').style.display = 'none';
    const detail = document.getElementById('toolDetail');
    detail.style.display = 'block';
    const customGuide = TOOL_GUIDES[tool.id];
    const categoryGuide = CATEGORY_GUIDES[tool.category] || { title: '使用说明', intro: '本工具在浏览器本地运行，您的数据不会上传到任何服务器，安全可靠。', steps: ['在输入框中填写需要处理的数据', '点击相应按钮执行操作', '结果会实时显示在输出区域', '可随时复制结果或下载文件'], tips: [] };
    const guideTitle = customGuide ? tool.name + '详细使用说明' : categoryGuide.title;
    const guideIntro = customGuide ? customGuide.intro : categoryGuide.intro;
    const guideSteps = customGuide ? customGuide.steps : categoryGuide.steps;
    const useCasesHtml = customGuide ? `<div class="tool-use-cases"><h3>🎯 应用场景</h3><p style="font-size:13px;color:var(--text-muted);margin-bottom:12px;">以下是「${tool.name}」在实际工作和生活中的常见应用场景：</p><ul>${customGuide.useCases.map(uc => `<li>${uc}</li>`).join('')}</ul></div>` : '';
    const faqHtml = customGuide ? `<div class="tool-faq"><h3>❓ 常见问题</h3>${customGuide.faq.map(f => { const parts = f.split('A:'); return `<div class="tool-faq-item"><div class="tool-faq-q">${parts[0].replace('Q:','')}</div><div class="tool-faq-a">${parts[1] || ''}</div></div>`; }).join('')}</div>` : '';
    const tipsHtml = (customGuide ? '' : (categoryGuide.tips.length > 0 ? `<h4 style="margin:16px 0 8px;font-size:15px;">使用技巧与注意事项</h4><ul>${categoryGuide.tips.map(t => `<li>${t}</li>`).join('')}</ul>` : ''));
    detail.innerHTML = `<button class="btn back-btn" onclick="window._backToList()">← 返回工具列表</button>
<div class="tool-detail-header"><div class="tool-detail-icon">${tool.icon}</div><div style="flex:1;"><h2>${tool.name}</h2><p>${tool.desc}</p><span class="tool-cat">${tool.category}</span></div><button class="favorite-btn ${isFavorite(tool.id) ? 'favorited' : ''}" id="favoriteBtn" data-tool="${tool.id}" title="${isFavorite(tool.id) ? '取消收藏' : '收藏工具'}">${isFavorite(tool.id) ? '★' : '☆'}</button></div>
<div class="ad-slot"><div class="ad-placeholder"><span class="ad-label">📢 广告</span><span class="ad-text">支持我们持续提供免费工具</span></div></div>
<div class="tool-detail-body">${tool.html}</div>
<div class="ad-slot"><div class="ad-placeholder"><span class="ad-label">📢 广告</span><span class="ad-text">您的支持是我们更新的动力</span></div></div>
<div class="tool-guide"><h3>${guideTitle}</h3><p>${guideIntro}</p><h4 style="margin:16px 0 8px;font-size:15px;">操作步骤</h4><ul>${guideSteps.map(s => `<li>${s}</li>`).join('')}</ul>${tipsHtml}</div>
${useCasesHtml}
${faqHtml}
<div class="related-tools"><h3>相关工具推荐</h3><p style="font-size:13px;color:var(--text-muted);margin-bottom:12px;">以下是与「${tool.name}」同分类的其他实用工具，点击即可使用</p><div class="related-tools-grid">${TOOLS.filter(t => t.category === tool.category && t.id !== tool.id).slice(0, 6).map(t => `<div class="tool-card related-tool-card" data-tool="${t.id}"><div class="tool-icon">${t.icon}</div><h3 class="tool-name">${t.name}</h3><p class="tool-desc">${t.desc}</p></div>`).join('')}</div></div>`;
    addRecentTool(tool.id);
    try { const script = document.createElement('script'); script.textContent = tool.js; detail.appendChild(script); } catch(e) { console.error('工具脚本执行失败:', e); }
    window.scrollTo({ top: 0, behavior: 'smooth' });
  }
  window._backToList = function() { document.getElementById('toolDetail').style.display = 'none'; document.getElementById('toolsGrid').style.display = 'grid'; };
  function renderBlogList() { const list = document.getElementById('blogList'); if (!list) return; list.innerHTML = BLOG_POSTS.map(post => `<article class="blog-card" data-blog="${post.id}"><div class="blog-card-icon">${post.icon}</div><div class="blog-card-content"><div class="blog-card-meta"><span class="blog-cat-tag">${post.category}</span><span class="blog-date">${post.date}</span><span class="blog-readtime">阅读约 ${post.readTime}</span></div><h3 class="blog-card-title">${post.title}</h3><p class="blog-card-summary">${post.summary}</p><span class="blog-read-more">阅读全文 →</span></div></article>`; }).join(''); }
  function renderLatestBlog() { const grid = document.getElementById('latestBlogGrid'); if (!grid) return; const latest = BLOG_POSTS.slice(0, 3); grid.innerHTML = latest.map(post => `<article class="blog-card blog-card-small" data-blog="${post.id}"><div class="blog-card-icon">${post.icon}</div><div class="blog-card-content"><div class="blog-card-meta"><span class="blog-cat-tag">${post.category}</span><span class="blog-date">${post.date}</span></div><h3 class="blog-card-title">${post.title}</h3><p class="blog-card-summary">${post.summary}</p></div></article>`; }).join(''); }
  function renderHotBlog() { const list = document.getElementById('hotBlogList'); if (!list) return; const hot = BLOG_POSTS.slice(0, 5); list.innerHTML = hot.map((post, i) => `<div class="hot-blog-item" data-blog="${post.id}"><span class="hot-blog-num">${i + 1}</span><span class="hot-blog-title">${post.title}</span></div>`; }).join(''); }
  function renderBlogCategories() { const list = document.getElementById('blogCategoryList'); if (!list) return; const cats = [...new Set(BLOG_POSTS.map(p => p.category))]; list.innerHTML = cats.map(cat => { const count = BLOG_POSTS.filter(p => p.category === cat).length; const catInfo = CATEGORIES.find(c => c.name === cat); return `<div class="blog-cat-item" data-blog-cat="${cat}"><span>${catInfo ? catInfo.icon : '📄'} ${cat}</span><span class="blog-cat-count">${count}</span></div>`; }).join(''); }
  function showBlog(blogId) { const post = BLOG_POSTS.find(p => p.id === blogId); if (!post) return; currentBlogId = blogId; const listEl = document.querySelector('.blog-layout'); const detailEl = document.getElementById('blogDetail'); if (listEl) listEl.style.display = 'none'; detailEl.style.display = 'block'; detailEl.innerHTML = `<button class="btn back-btn" onclick="window._backToBlogList()">← 返回教程列表</button><article class="blog-article"><div class="blog-article-header"><div class="blog-article-icon">${post.icon}</div><div class="blog-article-meta"><span class="blog-cat-tag">${post.category}</span><span class="blog-date">${post.date}</span><span class="blog-readtime">阅读约 ${post.readTime}</span></div><h1 class="blog-article-title">${post.title}</h1><p class="blog-article-summary">${post.summary}</p></div><div class="blog-article-content">${post.content}</div><div class="blog-article-footer"><p>如果这篇教程对您有帮助，欢迎分享给更多人。如有疑问或建议，请通过网站反馈渠道与我们联系。</p></div></article>`; window.scrollTo({ top: 0, behavior: 'smooth' }); }
  window._backToBlogList = function() { currentBlogId = null; const listEl = document.querySelector('.blog-layout'); const detailEl = document.getElementById('blogDetail'); if (listEl) listEl.style.display = 'grid'; detailEl.style.display = 'none'; };
  function renderFAQ() { const list = document.getElementById('faqList'); if (!list) return; list.innerHTML = FAQ_ITEMS.map((item, i) => `<div class="faq-item" data-faq="${i}"><div class="faq-question"><span class="faq-q-icon">Q</span><span class="faq-q-text">${item.question}</span><span class="faq-toggle">+</span></div><div class="faq-answer"><span class="faq-a-icon">A</span><div class="faq-a-text">${item.answer}</div></div></div>`; }).join(''); }
  function toggleFAQ(index) { const items = document.querySelectorAll('.faq-item'); items.forEach((item, i) => { if (i === index) { item.classList.toggle('open'); const toggle = item.querySelector('.faq-toggle'); if (toggle) toggle.textContent = item.classList.contains('open') ? '−' : '+'; } }); }
  function switchPage(page) { currentPage = page; document.querySelectorAll('.page').forEach(p => p.classList.remove('active')); document.getElementById(page).classList.add('active'); document.querySelectorAll('.nav-link').forEach(l => { l.classList.toggle('active', l.dataset.nav === page); }); if (page === 'tools') { document.getElementById('toolDetail').style.display = 'none'; document.getElementById('toolsGrid').style.display = 'grid'; } if (page === 'blog') { window._backToBlogList(); } window.scrollTo({ top: 0, behavior: 'smooth' }); }
  function bindEvents() {
    document.getElementById('themeToggle').addEventListener('click', toggleTheme);
    document.querySelectorAll('.nav-link').forEach(link => { link.addEventListener('click', function(e) { e.preventDefault(); switchPage(this.dataset.nav); history.pushState(null, '', '#' + this.dataset.nav); }); });
    document.getElementById('categoryList').addEventListener('click', function(e) { const item = e.target.closest('.category-item'); if (!item) return; currentCategory = item.dataset.cat; renderCategories(); renderTools(); });
    document.getElementById('categoryGrid').addEventListener('click', function(e) { const card = e.target.closest('.category-card'); if (!card) return; currentCategory = card.dataset.cat; renderCategories(); renderTools(); switchPage('tools'); history.pushState(null, '', '#tools'); });
    document.addEventListener('click', function(e) { const card = e.target.closest('.tool-card'); if (!card) return; switchPage('tools'); showTool(card.dataset.tool); history.pushState(null, '', '#tools'); });
    document.addEventListener('click', function(e) { const card = e.target.closest('[data-blog]'); if (!card) return; e.preventDefault(); switchPage('blog'); showBlog(card.dataset.blog); history.pushState(null, '', '#blog'); });
    document.getElementById('faqList').addEventListener('click', function(e) { const item = e.target.closest('.faq-item'); if (!item) return; const index = parseInt(item.dataset.faq); toggleFAQ(index); });
    const searchInput = document.getElementById('searchInput'); let searchTimer; if (searchInput) { searchInput.addEventListener('input', function() { clearTimeout(searchTimer); const kw = this.value; searchTimer = setTimeout(() => { if (kw.trim()) { switchPage('tools'); currentCategory = 'all'; renderCategories(); renderTools(kw); const sc = document.getElementById('searchCount'); if (sc) sc.textContent = `找到 ${TOOLS.filter(t => t.name.toLowerCase().includes(kw.toLowerCase()) || t.desc.toLowerCase().includes(kw.toLowerCase())).length} 个相关工具`; } else { const sc = document.getElementById('searchCount'); if (sc) sc.textContent = ''; renderTools(); } }, 300); }); }
    document.querySelectorAll('[data-tool]').forEach(link => { link.addEventListener('click', function(e) { e.preventDefault(); switchPage('tools'); showTool(this.dataset.tool); }); });
    document.addEventListener('click', function(e) { const favBtn = e.target.closest('.favorite-btn'); if (favBtn) { e.stopPropagation(); const toolId = favBtn.dataset.tool; const isFav = toggleFavorite(toolId); favBtn.classList.toggle('favorited', isFav); favBtn.textContent = isFav ? '★' : '☆'; favBtn.title = isFav ? '取消收藏' : '收藏工具'; renderFavoriteTools(); return; } const relatedCard = e.target.closest('.related-tool-card'); if (relatedCard) { e.stopPropagation(); showTool(relatedCard.dataset.tool); return; } });
    const contactForm = document.getElementById('contactForm'); if (contactForm) { contactForm.addEventListener('submit', function(e) { e.preventDefault(); const name = document.getElementById('contactName').value.trim(); const email = document.getElementById('contactEmail').value.trim(); const type = document.getElementById('contactType').value; const message = document.getElementById('contactMessage').value.trim(); const resultEl = document.getElementById('contactResult'); if (!name || !email || !message) { resultEl.innerHTML = '<div class="contact-result error">请填写所有必填项（姓名、邮箱、留言内容）</div>'; return; } if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) { resultEl.innerHTML = '<div class="contact-result error">请输入有效的邮箱地址</div>'; return; } try { const submissions = JSON.parse(localStorage.getItem('contactSubmissions') || '[]'); submissions.push({ name, email, type, message, date: new Date().toISOString() }); localStorage.setItem('contactSubmissions', JSON.stringify(submissions)); } catch(e) {} resultEl.innerHTML = '<div class="contact-result success">✅ 提交成功！感谢您的反馈，我们会认真阅读并尽快回复。</div>'; contactForm.reset(); }); }
    window.addEventListener('popstate', handleHash);
  }
  function handleHash() { const hash = location.hash.replace('#', '') || 'home'; if (['home', 'tools', 'about', 'privacy', 'terms', 'blog', 'faq', 'contact'].includes(hash)) { switchPage(hash); } else { switchPage('home'); } }
  function initAdSense() { try { (adsbygoogle = window.adsbygoogle || []).push({}); } catch(e) {} }
})();
